import { useState, useEffect } from "react";
import { useParams, useLocation, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft, Download } from "lucide-react";
import { Procedure } from "@/pages/Index";
import jsPDF from "jspdf";

const ReportEditor = () => {
  const { id } = useParams();
  const location = useLocation();
  const navigate = useNavigate();
  const procedure = location.state?.procedure as Procedure;

  const [reportContent, setReportContent] = useState("");

  useEffect(() => {
    if (procedure) {
      const initialReport = `ENDOSCOPIC PROCEDURE REPORT

Patient Information:
Name: ${procedure.patientName}
Patient ID: ${procedure.patientId}
Date: ${new Date(procedure.date).toLocaleDateString()}

Procedure Details:
Type: ${procedure.procedureType}
Surgeon: ${procedure.surgeon}
Duration: ${procedure.duration}
Anesthesia: ${procedure.anesthesia}

Findings:
${procedure.findings}

${procedure.complications ? `Complications:\n${procedure.complications}` : "Complications: None"}

---
This report was generated by EndoDoc - Endoscopic Surgery Documentation System`;
      
      setReportContent(initialReport);
    }
  }, [procedure]);

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const lines = doc.splitTextToSize(reportContent, 180);
    doc.setFontSize(12);
    doc.text(lines, 15, 15);
    doc.save(`${procedure.patientId}_report.pdf`);
  };

  if (!procedure) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <Card>
          <CardContent className="pt-6">
            <p className="text-muted-foreground">No procedure data found</p>
            <Button onClick={() => navigate("/")} className="mt-4">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Dashboard
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border bg-card shadow-sm">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Button variant="ghost" size="icon" onClick={() => navigate("/")}>
              <ArrowLeft className="w-5 h-5" />
            </Button>
            <div>
              <h1 className="text-2xl font-bold text-foreground">Report Editor</h1>
              <p className="text-sm text-muted-foreground">{procedure.patientName} - {procedure.patientId}</p>
            </div>
          </div>
          <Button onClick={handleDownloadPDF} className="gap-2">
            <Download className="w-4 h-4" />
            Download PDF
          </Button>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8">
        <Card className="shadow-lg">
          <CardHeader>
            <CardTitle>Edit Report Content</CardTitle>
          </CardHeader>
          <CardContent>
            <Textarea
              value={reportContent}
              onChange={(e) => setReportContent(e.target.value)}
              className="min-h-[600px] font-mono text-sm"
              placeholder="Edit the report content here..."
            />
          </CardContent>
        </Card>
      </main>
    </div>
  );
};

export default ReportEditor;
